"""
Hydrological models for DupuitLEM:
    HydrologySteadyStreamPower:
    - steady recharge
    HydrologyEventStreamPower:
    - stochastic recharge generated from landlab component PrecipitationDistribution
    HydrologyEventThresholdStreamPower
    - stochastic recharge generated from landlab component PrecipitationDistribution
    - approach allows for correct averaging of discharge when there is an incision threshold
    HydrologyEventVadoseStreamPower
    - stochastic precip generated by landlab component PrecipitationDistribution
    - precip and ET handled in vadose profile by SchenkVadoseModel
    - recharge is infiltration into vadose profile below water table, can occur during storms
    - stochastic precip generated by landlab component PrecipitationDistribution
    - precip and ET handled in vadose profile by SchenkVadoseModel
    - recharge is infiltration into vadose profile below water table, can occur during storms
    - approach allows for correct averaging of discharge when there is an incision threshold

    --------
    Notes:
    Designed for use with StreamPowerModel class. Calculate hydrological state
    and update fields that are used by FastscapeEroder in the StreamPowerModel
    to calculate erosion rates.


Author: David Litwin

Date: 19 May 2020
"""

import numpy as np

from landlab.components import (
    FlowDirectorD8,
    FlowDirectorSteepest,
    FlowAccumulator,
    LakeMapperBarnes,
    DepressionFinderAndRouter,
)


class HydrologicalModel:
    """
    Base class for hydrological model.

    Parameters
    -----
    grid: ModelGrid
        Landlab ModelGrid object. The Landlab component GroundwaterDupuitPercolator
        should be instantiated on the grid before instantiating a HydrologicalModel.
    routing_method: str
        Either 'D8' or 'Steepest'. This is the routing method for the FlowDirector
        component. 'Steepest' allows the use of non-raster grids.

    """

    def __init__(self, grid, routing_method):
        self._grid = grid

        if routing_method == "D8":
            self.fd = FlowDirectorD8(self._grid)
        elif routing_method == "Steepest":
            self.fd = FlowDirectorSteepest(self._grid)
        else:
            raise ValueError("routing_method must be either D8 or Steepest.")

        self.fa = FlowAccumulator(
            self._grid,
            surface="topographic__elevation",
            flow_director=self.fd,
            runoff_rate="average_surface_water__specific_discharge",
        )
        self.lmb = LakeMapperBarnes(
            self._grid,
            method=routing_method,
            fill_flat=False,
            surface="topographic__elevation",
            fill_surface="topographic__elevation",
            redirect_flow_steepest_descent=False,
            reaccumulate_flow=False,
            track_lakes=False,
            ignore_overfill=True,
        )
        self.dfr = DepressionFinderAndRouter(self._grid)

    def run_step(self):
        raise NotImplementedError


class HydrologySteadyStreamPower(HydrologicalModel):
    """ "
    Run hydrological model for steady recharge provided to the
    GroundwaterDupuitPercolator. HydrologySteadyStreamPower is meant to be
    passed to the StreamPowerModel, where erosion rate is calculated.
    An additional field, surface_water_area_norm__discharge is calculated
    by dividing the effective discharge by the square root of the drainage area.
    This accounts for how channel width varies with the square root of area.
    When combined with FastscapeEroder with m=1 and n=1, this produces erosion
    with the form E = K v0 Q* sqrt(a) S, where Q*=Q/(pA).
    """

    def __init__(
        self,
        grid,
        routing_method="D8",
        groundwater_model=None,
        hydrological_timestep=1e5,
    ):
        """
        Parameters
        -----
        grid: ModelGrid
            Landlab ModelGrid object. The Landlab component GroundwaterDupuitPercolator
            should be instantiated on the grid before instantiating a HydrologicalModel.
        routing_method: str
            Either 'D8' or 'Steepest'. This is the routing method for the FlowDirector
            component. 'Steepest' allows the use of non-raster grids.
            Default: 'D8'
        groundwater_model: GroundwaterDupuitPercolator
            Landlab GroundwaterDupuitPercolator Component object that is instantiated
            on the supplied grid.
            Default: None
        hydrological_timestep: float
            Time over which to run one step of the HydrologicalModel. In the steady
            recharge case this is also the timestep for which the groundwater model
            is run.
            Default: 1e5
        """

        super().__init__(grid, routing_method)

        self.gdp = groundwater_model
        self.T_h = hydrological_timestep

        self.q_an = self._grid.add_zeros("node", "surface_water_area_norm__discharge")
        self.area = self._grid.at_node["drainage_area"]
        self.q = self._grid.at_node["surface_water__discharge"]

    def run_step(self):
        """
        Run steady model one step. Update groundwater state, route and accumulate
        flow, updating surface_water__discharge and surface_water_area_norm__discharge.
        """

        # run gw model
        self.gdp.run_with_adaptive_time_step_solver(self.T_h)
        self.number_substeps = self.gdp.number_of_substeps

        # find pits for flow accumulation
        self.dfr._find_pits()
        if self.dfr._number_of_pits > 0:
            self.lmb.run_one_step()

        # run flow accumulation on average_surface_water__specific_discharge
        self.fa.run_one_step()

        # add a criteria that effectively cuts Q* off at 1 (greater due to numerical issues)
        # this is less of an issue with the new analytical solution for wt rise in gdp.
        qmax = self.gdp.recharge * self.area
        self.q[self.q > qmax] = qmax[self.q > qmax]

        # discharge field with form for Q*
        self.q_an[:] = np.divide(
            self.q, np.sqrt(self.area), where=self.area > 0, out=np.zeros_like(self.q)
        )

class HydrologyEventVadoseStreamPower(HydrologicalModel):
    """ "
    This model considers stochastic storm event duration, interevent duration, and intensity
    for the case where there is vadose zone storage and evapotranspiration. The SchenkVadoseModel
    is used to determine recharge of water to the water table in storm events and interevents r
    espectively. One vadose profile is tracked and this is used to map recharge and extraction rates based on
    depth to water table across grid. Field "recharge_rate" is added as recharge can vary spatially.
    Mean precipitation and contant PET can vary with elevation if lapse functions are supplied, but 
    still must be single values. 
    """

    def __init__(
        self,
        grid,
        routing_method="D8",
        precip_generator=None,
        groundwater_model=None,
        vadose_model=None,
        precip_lapse_function=None,
        pet_lapse_function=None,
    ):
        """
        Parameters
        -----
        grid: ModelGrid
            Landlab ModelGrid object. The Landlab component GroundwaterDupuitPercolator
            should be instantiated on the grid before instantiating a HydrologicalModel.
        routing_method: str
            Either 'D8' or 'Steepest'. This is the routing method for the FlowDirector
            component. 'Steepest' allows the use of non-raster grids.
            Default: 'D8'
        precip_generator: PrecipitationDistribution
            Landlab PrecipitationDistribution Component object. The HydrologicalModel
            will run one step for the length of time intantiated in this object.
            Default: None
        groundwater_model: GroundwaterDupuitPercolator
            Landlab GroundwaterDupuitPercolator Component object that is instantiated
            on the supplied grid.
            Default: None
        vadose_model: SchenkVadoseModel
            Auxiliary model called SchenkVadoseModel, instantiated for a depth profile
            equal to the permeable thickness.
            Default: None
        precip_lapse_function: function
            A function that takes in mean storm depth and elevation, and
            returns a modified mean storm depth. This allows for the
            inclusion of a lapse rate for precip. The function should take the form
            f(mean_storm_depth, elevation) and return modified_mean_storm_depth. Default: None
        pet_lapse_function: function
            A function that takes in the potential evapotranspiration rate and elevation, and
            returns a modified potential evapotranspiration rate. This allows for the
            inclusion of a lapse rate for pet. The function should take the form
            f(pet, elevation) and return modified_pet. Default: None
        """
        super().__init__(grid, routing_method)

        self.q_eff = self._grid.add_zeros("node", "surface_water_effective__discharge")
        self.q_an = self._grid.add_zeros("node", "surface_water_area_norm__discharge")
        self.area = self._grid.at_node["drainage_area"]
        self.qs = self._grid.at_node["average_surface_water__specific_discharge"]
        self.pd = precip_generator
        self.gdp = groundwater_model
        self.T_h = self.pd._run_time

        self.svm = vadose_model
        self._base_pet = self.svm.pet
        self._base_p = self.pd._mean_storm_depth / (self.pd._mean_interstorm_duration + self.pd._mean_storm_duration)

        self.r = self._grid.add_zeros("node", "recharge_rate")
        self._elev = self._grid.at_node["topographic__elevation"]
        self._wt = self._grid.at_node["water_table__elevation"]

        self.precip_lapse_function = precip_lapse_function
        self.pet_lapse_function = pet_lapse_function

    def generate_precip(self):
        """
        Generate all storms ahead of time.
        """

        storm_dts = []
        interstorm_dts = []
        intensities = []

        for storm_dt, interstorm_dt in self.pd.yield_storms():
            storm_dts.append(storm_dt)
            interstorm_dts.append(interstorm_dt)
            intensities.append(float(self._grid.at_grid["rainfall__flux"]))

        self.storm_dts = storm_dts
        self.interstorm_dts = interstorm_dts
        self.intensities = intensities

    def run_step(self, record_state=False):
        """
        Run hydrological model for series of event-interevent pairs, calculating the
        total surface runoff produced at the end of each event and interevent, and then
        routing this at the end.

        Optional recording of state:

        track the state of the model:
            time: (s)
            intensity: rainfall intensity (m/s)
            wt_all: water table elevation (m)
            qs_all: surface water specific discharge (m/s)
            Q_all: discharge (m3/s)
            r_all: recharge rate (m/s)

        also track some cumulative quantities:
            cum_precip: cumulative precipitation (m3)
            cum_recharge: cumulative recharge (m3)
            cum_runoff:  cumulative runoff (m3)
            cum_gw_export:  cumulative groundwater export through open boundaries (m3)
            cum_pet:  cumulative potential evapotranspiration (m3)

        and some vadose profile features:
            cum_recharge_profile: cumulative recharge with depth in the vadose profile
            bool_recharge_profile: boolean of depths at which recharge occurs
            mean_recharge_depth: Mean depth of recharge at wt depth given recharge
                occurred. cum_recharge_profile/bool_recharge_profile
            recharge_frequency: frequency of recharge events at wt depth.
                bool_recharge_profile/T_h
        """
        cores = self._grid.core_nodes

        # if pet lapse function, update pet in vadose model
        if self.pet_lapse_function is not None:
            pet = self.pet_lapse_function(self._base_pet, self._elev)
            self.svm.pet = pet

        # if precip lapse function, update mean storm depth in precip generator and regenerate storms
        if self.precip_lapse_function is not None:
            mean_p = self.precip_lapse_function(self._base_p, self._elev)
            self.pd._mean_storm_depth = mean_p * (self.pd._mean_interstorm_duration + self.pd._mean_storm_duration)

        # generate new precip time series
        self.generate_precip()

        # find and route flow if there are pits
        self.dfr._find_pits()
        if self.dfr._number_of_pits > 0:
            self.lmb.run_one_step()

        # update flow directions
        self.fd.run_one_step()

        if record_state:
            # fields to record:
            Ns = 2 * len(self.storm_dts) + 1
            N = len(self.q_eff)
            self.time = np.zeros(Ns)
            self.intensity = np.zeros(Ns)
            self.Q_all = np.zeros((Ns, N)) # all discharge
            self.wt_all = np.zeros((Ns, N)) # water table elevation
            self.wt_all[0, :] = self._grid.at_node["water_table__elevation"].copy()
            self.qs_all = np.zeros((Ns, N))             # all surface water specific discharge
            self.r_all = np.zeros((Ns, N))            # all recharge

            # vadose profile properties
            self.cum_recharge_profile = np.zeros_like(self.svm.depths)
            self.bool_recharge_profile = np.zeros_like(self.svm.depths)

            # precip/recharge spatially-averaged properties
            areas = self._grid.cell_area_at_node[cores]
            obn = self._grid.open_boundary_nodes
            self.cum_precip = 0.0
            self.cum_recharge = 0.0
            self.cum_runoff = 0.0
            self.cum_gw_export = 0.0
            self.cum_pet = 0.0

        self.max_substeps_storm = 0
        self.max_substeps_interstorm = 0
        q_total = np.zeros_like(self.q_eff)
        for i, (storm_dt, interstorm_dt, intensity) in enumerate(zip(self.storm_dts, self.interstorm_dts, self.intensities)):

            # run event:
            ## run vadose model, calculate recharge based on depth to wt
            self.svm.run_event(intensity * storm_dt)
            wt_from_surface = self._elev[cores] - self._wt[cores]
            self.r[cores] = self.svm.calc_recharge_rate(wt_from_surface, storm_dt)

            ## set recharge, run groundwater model, accumulate flow
            self.gdp.recharge = self.r
            self.gdp.run_with_adaptive_time_step_solver(storm_dt)
            q_total += self.qs * storm_dt
            self.max_substeps_storm = max(
                self.max_substeps_storm, self.gdp.number_of_substeps
            )

            if record_state:
                # if recording state, accumulate flow to get discharge at end of event, and record state
                _, q = self.fa.accumulate_flow(update_flow_director=False)
                q1 = q.copy()
                self.max_substeps_storm = max(
                    self.max_substeps_storm, self.gdp.number_of_substeps
                )
                qgw1 = self.gdp.calc_gw_flux_out()

                # record event
                self.time[i * 2 + 1] = self.time[i * 2] + storm_dt
                self.intensity[i * 2] = intensity
                self.r_all[i * 2, :] = self._grid.at_node["recharge_rate"]
                self.Q_all[i * 2 + 1, :] = self._grid.at_node["surface_water__discharge"]
                self.wt_all[i * 2 + 1, :] = self._grid.at_node["water_table__elevation"]
                self.qs_all[i * 2 + 1, :] = self._grid.at_node[
                    "average_surface_water__specific_discharge"
                ]

            # run interevent:
            interstorm_dt = max(interstorm_dt, 1e-15)  # avoid some nans
            self.svm.run_interevent(interstorm_dt)

            # run groundwater model, accumulate flow
            self.gdp.recharge = 0.0
            self.gdp.run_with_adaptive_time_step_solver(interstorm_dt)
            q_total += self.qs * interstorm_dt
            self.max_substeps_interstorm = max(
                self.max_substeps_interstorm, self.gdp.number_of_substeps
            )

            if record_state:
                # if recording state, accumulate flow to get discharge at end of interevent, and record state
                _, q = self.fa.accumulate_flow(update_flow_director=False)
                q2 = q.copy()
                self.max_substeps_interstorm = max(
                    self.max_substeps_interstorm, self.gdp.number_of_substeps
                )
                qgw2 = self.gdp.calc_gw_flux_out()

                # record interevent
                self.time[i * 2 + 2] = self.time[i * 2 + 1] + interstorm_dt
                self.Q_all[i * 2 + 2, :] = self._grid.at_node["surface_water__discharge"]
                self.wt_all[i * 2 + 2, :] = self._grid.at_node["water_table__elevation"]
                self.qs_all[i * 2 + 2, :] = self._grid.at_node[
                    "average_surface_water__specific_discharge"
                ]

                # record vadose characteristics
                self.cum_recharge_profile += self.svm.recharge_at_depth
                self.bool_recharge_profile += self.svm.recharge_at_depth > 0.0

                # record precip/recharge spatially-averaged characteristics
                self.cum_precip += np.sum(intensity * areas) * storm_dt
                self.cum_pet += np.sum(self.svm.pet * areas) * interstorm_dt
                self.cum_recharge += np.sum(self.r[cores] * areas) * storm_dt
                self.cum_runoff += np.sum(q1[obn] * storm_dt + q2[obn] * interstorm_dt)
                self.cum_gw_export += np.sum(qgw1 * storm_dt + qgw2 * interstorm_dt)

        # set effective runoff rates
        self.qs[:] = q_total / self.T_h
        _, Q = self.fa.accumulate_flow(update_flow_director=False)

        self.q_eff[:] = Q
        self.q_an[:] = np.divide(
            self.q_eff,
            np.sqrt(self.area),
            where=self.area > 0,
            out=np.zeros_like(self.q_eff),
        )

        if record_state:
            # derived properties
            # mean recharge at each vadose profile
            self.mean_recharge_depth = (
                self.cum_recharge_profile / self.bool_recharge_profile
            )
            # frequency of recharge in vadose profile
            self.recharge_frequency = self.bool_recharge_profile / self.T_h


class HydrologyEventVadoseThresholdStreamPower(HydrologyEventVadoseStreamPower):
    """
    This model considers stochastic storm event duration, interevent duration, and intensity
    for the case where there is vadose zone storage and evapotranspiration, adding the effect of 
    thresholds for fluvial erosion. The SchenkVadoseModel is used to determine recharge of water to 
    the water table in storm events and interevents respectively. One vadose profile is tracked and 
    this is used to map recharge and extraction rates based on depth to water table across grid. Field 
    "recharge_rate" is added as recharge can vary spatially. Mean precipitation and contant PET can 
    vary with elevation if lapse functions are supplied, but still must be single values. 

    Rather than tracking discharge at storms and interstorms, erosion-producing
    discharge Q-Q0 is tracked, and returned in a fashion that is correctly
    averaged with threshold accounted for in the field "surface_water_effective__discharge".
    CONSEQUENTLY ONE SHOULD LEAVE THE INCISION THRESHOLD FIELD OF
    FastscapeEroder SET TO ZERO! For the same reason, this field has a different
    meaning when using the threshold model: it is not an actual discharge,
    but an effective value that also accounts for geomorphic properties related
    to the threshold streampower.
    """

    def __init__(
        self,
        grid,
        routing_method="D8",
        precip_generator=None,
        groundwater_model=None,
        vadose_model=None,
        sp_threshold=0.0,
        sp_coefficient=1e-5,
        precip_lapse_function=None,
        pet_lapse_function=None,
    ):
        """
        Parameters
        -----
        grid: ModelGrid
            Landlab ModelGrid object. The Landlab component GroundwaterDupuitPercolator
            should be instantiated on the grid before instantiating a HydrologicalModel.
        routing_method: str
            Either 'D8' or 'Steepest'. This is the routing method for the FlowDirector
            component. 'Steepest' allows the use of non-raster grids.
            Default: 'D8'
        precip_generator: PrecipitationDistribution
            Landlab PrecipitationDistribution Component object. The HydrologicalModel
            will run one step for the length of time intantiated in this object.
            Default: None
        groundwater_model: GroundwaterDupuitPercolator
            Landlab GroundwaterDupuitPercolator Component object that is instantiated
            on the supplied grid.
            Default: None
        vadose_model: SchenkVadoseModel
            Auxiliary model called SchenkVadoseModel, instantiated for a depth profile
            equal to the permeable thickness.
            Default: None
        sp_threshold: float
            the streampower incision threshold E0 in the equation
            E = K Q* sqrt(a v0) S - E0, where Q*=Q/(pA). Units: L/T
            Default: 0.0
        sp_coefficient: float
            streampower coefficient used in the FastscapeEroder
            component. Note that in DupuitLEM, the expected value has units 1/L,
            because it takes a coefficient K/p, where K is the usual streampower
            coefficient, with units 1/T, and p is the mean precipitation rate with
            units L/T.
            Default: 1e-5
        precip_lapse_function: function
            A function that takes in mean storm depth and elevation, and
            returns a modified mean storm depth. This allows for the
            inclusion of a lapse rate for precip. The function should take the form
            f(mean_storm_depth, elevation) and return modified_mean_storm_depth. Default: None
        pet_lapse_function: function
            A function that takes in the potential evapotranspiration rate and elevation, and
            returns a modified potential evapotranspiration rate. This allows for the
            inclusion of a lapse rate for pet. The function should take the form
            f(pet, elevation) and return modified_pet. Default: None
        """

        super().__init__(grid, routing_method, precip_generator, groundwater_model, vadose_model, precip_lapse_function, pet_lapse_function )

        self.E0 = sp_threshold
        self.Ksp = sp_coefficient
        self.Q0 = self._grid.add_zeros("node", "critical_erosion__discharge")
        self._receivers = self._grid.at_node["flow__link_to_receiver_node"]

        if routing_method == "D8":
            self._calc_grad = self._grid.calc_grad_at_d8
        else:
            self._calc_grad = self._grid.calc_grad_at_link

    
    def run_step(self, record_state=False):
        """
        Run hydrological model for series of event-interevent pairs, calculate
        flow rates at end of events and interevents over total_hydrological_time.
        Initially generate exponential precip, fill pits, find flow directions,
        calculate critical erosion rate. Through storm-interstorm pairs,
        update vadose model state, calculate recharge, update groundwater state,
        route flow, calculate additional erosion-generating flow. After, calculate
        surface_water_effective__discharge and surface_water_area_norm__discharge.

        Optional recording of state:

        track the state of the model:
            time: (s)
            intensity: rainfall intensity (m/s)
            wt_all: water table elevation (m)
            qs_all: surface water specific discharge (m/s)
            Q_all: discharge (m3/s)
            r_all: recharge rate (m/s)

        also track some cumulative quantities:
            cum_precip: cumulative precipitation (m3)
            cum_recharge: cumulative recharge (m3)
            cum_runoff:  cumulative runoff (m3)
            cum_gw_export:  cumulative groundwater export through open boundaries (m3)
            cum_pet:  cumulative potential evapotranspiration (m3)

        and some vadose profile features:
            cum_recharge_profile: cumulative recharge with depth in the vadose profile
            bool_recharge_profile: boolean of depths at which recharge occurs
            mean_recharge_depth: Mean depth of recharge at wt depth given recharge
                occurred. cum_recharge_profile/bool_recharge_profile
            recharge_frequency: frequency of recharge events at wt depth.
                bool_recharge_profile/T_h
        """
        cores = self._grid.core_nodes

        # if pet lapse function, update pet in vadose model
        if self.pet_lapse_function is not None:
            pet = self.pet_lapse_function(self._base_pet, self._elev)
            self.svm.pet = pet

        # if precip lapse function, update mean storm depth in precip generator and regenerate storms
        if self.precip_lapse_function is not None:
            mean_p = self.precip_lapse_function(self._base_p, self._elev)
            self.pd._mean_storm_depth = mean_p * (self.pd._mean_interstorm_duration + self.pd._mean_storm_duration)

        # generate new precip time series
        self.generate_precip()

        # find and route flow if there are pits
        self.dfr._find_pits()
        if self.dfr._number_of_pits > 0:
            self.lmb.run_one_step()

        # update flow directions
        self.fd.run_one_step()

        # calculate critical_erosion__discharge
        dzdx = self._calc_grad(self._elev)
        S = abs(dzdx[self._receivers])  # slope is in direction of flow
        _, _ = self.fa.accumulate_flow(update_flow_director=False)  # to update area
        self.Q0[:] = np.divide(
            self.E0 * np.sqrt(self.area),
            self.Ksp * S,
            where=S > 0.0,
            out=np.zeros_like(S),
        )

        if record_state:
            # fields to record:
            Ns = 2 * len(self.storm_dts) + 1
            N = len(self.q_eff)
            self.time = np.zeros(Ns)
            self.intensity = np.zeros(Ns)
            # all discharge
            self.Q_all = np.zeros((Ns, N))
            # water table elevation
            self.wt_all = np.zeros((Ns, N))
            self.wt_all[0, :] = self._grid.at_node["water_table__elevation"].copy()
            # all surface water specific discharge
            self.qs_all = np.zeros((Ns, N))
            self.r_all = np.zeros((Ns, N))

            # vadose profile properties
            self.cum_recharge_profile = np.zeros_like(self.svm.depths)
            self.bool_recharge_profile = np.zeros_like(self.svm.depths)

            # precip/recharge spatially-averaged properties
            areas = self._grid.cell_area_at_node[cores]
            obn = self._grid.open_boundary_nodes
            self.cum_precip = 0.0
            self.cum_recharge = 0.0
            self.cum_runoff = 0.0
            self.cum_gw_export = 0.0
            self.cum_pet = 0.0

        self.max_substeps_storm = 0
        self.max_substeps_interstorm = 0

        # initialize total volume above threshold for each node, to be divided by total time at end
        q_total_vol_t = np.zeros_like(self.q_eff)
        # q2 = np.zeros_like(self.q_eff)
        for i, (storm_dt, interstorm_dt, intensity) in enumerate(zip(self.storm_dts, self.interstorm_dts, self.intensities)):
            # q0 = q2.copy()  # save prev end of interstorm flow rate

            # run event:
            ## run vadose model, calculate recharge based on depth to wt
            self.svm.run_event(intensity * storm_dt)
            wt_from_surface = self._elev[cores] - self._wt[cores]
            wt_from_surface[wt_from_surface > self.svm.b] = self.svm.b - 1e-15
            self.r[cores] = self.svm.calc_recharge_rate(
                wt_from_surface, storm_dt
            )

            ## set recharge, run groundwater model, accumulate flow
            self.gdp.recharge = self.r
            self.gdp.run_with_adaptive_time_step_solver(storm_dt)
            _, q1 = self.fa.accumulate_flow(update_flow_director=False)
            q1_t = np.maximum(q1 - self.Q0, 0.0)
            self.max_substeps_storm = max(
                self.max_substeps_storm, self.gdp.number_of_substeps
            )

            if record_state:
                Qgw1 = self.gdp.calc_gw_flux_out()

                # record event
                self.time[i * 2 + 1] = self.time[i * 2] + storm_dt
                self.intensity[i * 2] = intensity
                self.r_all[i * 2, :] = self._grid.at_node["recharge_rate"]
                self.Q_all[i * 2 + 1, :] = self._grid.at_node["surface_water__discharge"]
                self.wt_all[i * 2 + 1, :] = self._grid.at_node["water_table__elevation"]
                self.qs_all[i * 2 + 1, :] = self._grid.at_node[
                    "average_surface_water__specific_discharge"
                ]

            # run interevent:
            ## run vadose model, calculate the extraction below the water table
            ## due to ET.
            interstorm_dts = max(
                interstorm_dt, 1e-15
            )  # avoid some nans
            self.svm.run_interevent(interstorm_dts)

            # set run groundwater model, accumulate flow
            self.gdp.recharge = 0.0
            self.gdp.run_with_adaptive_time_step_solver(interstorm_dts)
            _, q2 = self.fa.accumulate_flow(update_flow_director=False)
            q2_t = np.maximum(q2 - self.Q0, 0.0)
            self.max_substeps_interstorm = max(
                self.max_substeps_interstorm, self.gdp.number_of_substeps
            )

            # record interevent
            if record_state:
                Qgw2 = self.gdp.calc_gw_flux_out()

                self.time[i * 2 + 2] = self.time[i * 2 + 1] + interstorm_dts
                self.Q_all[i * 2 + 2, :] = self._grid.at_node["surface_water__discharge"]
                self.wt_all[i * 2 + 2, :] = self._grid.at_node["water_table__elevation"]
                self.qs_all[i * 2 + 2, :] = self._grid.at_node[
                    "average_surface_water__specific_discharge"
                ]

                # record vadose characteristics
                self.cum_recharge_profile += self.svm.recharge_at_depth
                self.bool_recharge_profile += self.svm.recharge_at_depth > 0.0

                # record precip/recharge spatially-averaged characteristics
                self.cum_precip += np.sum(intensity * areas) * storm_dt
                self.cum_recharge += np.sum(self.r[cores] * areas) * storm_dt
                self.cum_runoff += np.sum(q1[obn] * storm_dt + q2[obn] * interstorm_dts)
                self.cum_pet += np.sum(self.svm.pet * areas) * interstorm_dts
                self.cum_gw_export += np.sum(Qgw2 * interstorm_dts) + np.sum(Qgw1 * storm_dt)

            # volume of runoff contributed during timestep above threshold
            q_total_vol_t += q1_t * storm_dt + q2_t * interstorm_dts

        self.q_eff[:] = q_total_vol_t / self.T_h
        self.q_an[:] = np.divide(
            self.q_eff,
            np.sqrt(self.area),
            where=self.area > 0,
            out=np.zeros_like(self.q_eff),
        )

        if record_state:
            # derived properties
            # mean recharge at each vadose profile
            self.mean_recharge_depth = (
                self.cum_recharge_profile / self.bool_recharge_profile
            )
            # frequency of recharge in vadose profile
            self.recharge_frequency = self.bool_recharge_profile / self.T_h
